"""Alter table Todos, add access token and refresh token

Revision ID: bc46fc570e2c
Revises: 6fc880372153
Create Date: 2023-12-18 14:10:53.603170

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc46fc570e2c'
down_revision = '6fc880372153'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('access_token', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('refresh_token', sa.Text(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todos', schema=None) as batch_op:
        batch_op.drop_column('refresh_token')
        batch_op.drop_column('access_token')

    # ### end Alembic commands ###
